package com.cebomberman.game.graphics;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author 
 */
public class GameStarter extends javax.swing.JFrame {

	/**
	 * Creates new form GameStarterGui
	 */
	public GameStarter() {
		try {
			// Set System L&F
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (UnsupportedLookAndFeelException e) {
			// handle exception
		} catch (ClassNotFoundException e) {
			// handle exception
		} catch (InstantiationException e) {
			// handle exception
		} catch (IllegalAccessException e) {
			// handle exception
		}
		GameStarterComponents panel = new GameStarterComponents();
		setBounds(0, 0, 680, 330);
		add(panel);
		setVisible(true);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		menuBar = new javax.swing.JMenuBar();
		file = new javax.swing.JMenu();
		launchGame = new javax.swing.JMenuItem();
		openMap = new javax.swing.JMenuItem();
		exitPartSeperator = new javax.swing.JPopupMenu.Separator();
		exit = new javax.swing.JMenuItem();
		quit = new javax.swing.JMenuItem();
		edit = new javax.swing.JMenu();
		cut = new javax.swing.JMenuItem();
		copy = new javax.swing.JMenuItem();
		paste = new javax.swing.JMenuItem();
		Window = new javax.swing.JMenu();
		mapEditor = new javax.swing.JMenuItem();
		highScore = new javax.swing.JMenuItem();
		help = new javax.swing.JMenu();
		helpContents = new javax.swing.JMenuItem();
		about = new javax.swing.JMenuItem();
		license = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setPreferredSize(new java.awt.Dimension(680, 340));

		file.setText("File");

		launchGame.setText("Launch Game");
		file.add(launchGame);

		openMap.setText("Open Map");
		file.add(openMap);
		file.add(exitPartSeperator);

		exit.setText("Exit");
		file.add(exit);

		quit.setText("Quit");
		file.add(quit);

		menuBar.add(file);

		edit.setText("Edit");

		cut.setText("Cut");
		edit.add(cut);

		copy.setText("Copy");
		edit.add(copy);

		paste.setText("Paste");
		edit.add(paste);

		menuBar.add(edit);

		Window.setText("Window");

		mapEditor.setText("Map Editor");
		Window.add(mapEditor);

		highScore.setText("High Scores");
		Window.add(highScore);

		menuBar.add(Window);

		help.setText("Help");

		helpContents.setText("Help Contents");
		help.add(helpContents);

		about.setText("About");
		help.add(about);

		license.setText("License");
		help.add(license);

		menuBar.add(help);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 641,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 311,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JMenu Window;
	private javax.swing.JMenuItem about;
	private javax.swing.JMenuItem copy;
	private javax.swing.JMenuItem cut;
	private javax.swing.JMenu edit;
	private javax.swing.JMenuItem exit;
	private javax.swing.JPopupMenu.Separator exitPartSeperator;
	private javax.swing.JMenu file;
	private javax.swing.JMenu help;
	private javax.swing.JMenuItem helpContents;
	private javax.swing.JMenuItem highScore;
	private javax.swing.JMenuItem launchGame;
	private javax.swing.JMenuItem license;
	private javax.swing.JMenuItem mapEditor;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMap;
	private javax.swing.JMenuItem paste;
	private javax.swing.JMenuItem quit;
	// End of variables declaration
}
