package com.cebomberman.game.graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author smmsadrnezh
 */
public class GameBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form GameBoardPanel
     */
    public GameBoardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        openGameStarter = new javax.swing.JToggleButton();
        gameLogo = new javax.swing.JLabel();
        ceBomberman = new javax.swing.JLabel();
        player1 = new javax.swing.JPanel();
        nickName = new javax.swing.JLabel();
        lifeNumber = new javax.swing.JLabel();
        bombNumber = new javax.swing.JLabel();
        player2 = new javax.swing.JPanel();
        nickName1 = new javax.swing.JLabel();
        lifeNumber1 = new javax.swing.JLabel();
        bombNumber1 = new javax.swing.JLabel();
        player3 = new javax.swing.JPanel();
        nickName2 = new javax.swing.JLabel();
        lifeNumber2 = new javax.swing.JLabel();
        bombNumber2 = new javax.swing.JLabel();
        player4 = new javax.swing.JPanel();
        nickName3 = new javax.swing.JLabel();
        lifeNumber3 = new javax.swing.JLabel();
        bombNumber3 = new javax.swing.JLabel();
        countdown = new javax.swing.JLabel();
        timerProgressBar = new javax.swing.JProgressBar();
        gameStarter = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        fx = new javax.swing.JButton();
        music = new javax.swing.JButton();

        openGameStarter.setText("Game Starter");
        openGameStarter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openGameStarterActionPerformed(evt);
            }
        });

        gameLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameLogo.setIcon(new javax.swing.ImageIcon("/home/smmsadrnezh/NetBeansProjects/GameStarterGui/images/logo.png")); // NOI18N

        ceBomberman.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        ceBomberman.setForeground(new java.awt.Color(1, 1, 1));
        ceBomberman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ceBomberman.setText("CE Bomberman");

        player1.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 1"));

        nickName.setText("Nickname ");

        lifeNumber.setText("LifeNumber");

        bombNumber.setText("BombNumber");

        javax.swing.GroupLayout player1Layout = new javax.swing.GroupLayout(player1);
        player1.setLayout(player1Layout);
        player1Layout.setHorizontalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1Layout.createSequentialGroup()
                .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickName)
                    .addComponent(lifeNumber)
                    .addComponent(bombNumber))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        player1Layout.setVerticalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1Layout.createSequentialGroup()
                .addComponent(nickName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombNumber)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        player2.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 2"));

        nickName1.setText("Nickname ");

        lifeNumber1.setText("LifeNumber");

        bombNumber1.setText("BombNumber");

        javax.swing.GroupLayout player2Layout = new javax.swing.GroupLayout(player2);
        player2.setLayout(player2Layout);
        player2Layout.setHorizontalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickName1)
                    .addComponent(lifeNumber1)
                    .addComponent(bombNumber1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        player2Layout.setVerticalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addComponent(nickName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombNumber1)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        player3.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 4"));

        nickName2.setText("Nickname ");

        lifeNumber2.setText("LifeNumber");

        bombNumber2.setText("BombNumber");

        javax.swing.GroupLayout player3Layout = new javax.swing.GroupLayout(player3);
        player3.setLayout(player3Layout);
        player3Layout.setHorizontalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3Layout.createSequentialGroup()
                .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickName2)
                    .addComponent(lifeNumber2)
                    .addComponent(bombNumber2))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        player3Layout.setVerticalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3Layout.createSequentialGroup()
                .addComponent(nickName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeNumber2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombNumber2)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        player4.setBorder(javax.swing.BorderFactory.createTitledBorder("Player 3"));

        nickName3.setText("Nickname ");

        lifeNumber3.setText("LifeNumber");

        bombNumber3.setText("BombNumber");

        javax.swing.GroupLayout player4Layout = new javax.swing.GroupLayout(player4);
        player4.setLayout(player4Layout);
        player4Layout.setHorizontalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4Layout.createSequentialGroup()
                .addGroup(player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nickName3)
                    .addComponent(lifeNumber3)
                    .addComponent(bombNumber3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        player4Layout.setVerticalGroup(
            player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4Layout.createSequentialGroup()
                .addComponent(nickName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lifeNumber3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bombNumber3)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        countdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countdown.setText("timer");

        gameStarter.setText("Game Starter");
        gameStarter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameStarterKeyPressed(evt);
            }
        });

        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        fx.setText("FX");
        fx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fxMouseClicked(evt);
            }
        });
        fx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fxActionPerformed(evt);
            }
        });

        music.setText("Music");
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musicMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fx, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(music, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gameLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timerProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(countdown, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ceBomberman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gameStarter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ceBomberman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countdown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameStarter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fx)
                    .addComponent(music))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void openGameStarterActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void fxActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {                                  

    }                                 

    private void gameStarterKeyPressed(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void fxMouseClicked(java.awt.event.MouseEvent evt) {                                
        // TODO add your handling code here:
    }                               

    private void musicMousePressed(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
    }                                  


    // Variables declaration - do not modify                     
    private javax.swing.JLabel bombNumber;
    private javax.swing.JLabel bombNumber1;
    private javax.swing.JLabel bombNumber2;
    private javax.swing.JLabel bombNumber3;
    private javax.swing.JLabel ceBomberman;
    private javax.swing.JLabel countdown;
    private javax.swing.JButton exit;
    private javax.swing.JButton fx;
    private javax.swing.JLabel gameLogo;
    private javax.swing.JButton gameStarter;
    private javax.swing.JLabel lifeNumber;
    private javax.swing.JLabel lifeNumber1;
    private javax.swing.JLabel lifeNumber2;
    private javax.swing.JLabel lifeNumber3;
    private javax.swing.JButton music;
    private javax.swing.JLabel nickName;
    private javax.swing.JLabel nickName1;
    private javax.swing.JLabel nickName2;
    private javax.swing.JLabel nickName3;
    private javax.swing.JToggleButton openGameStarter;
    private javax.swing.JPanel player1;
    private javax.swing.JPanel player2;
    private javax.swing.JPanel player3;
    private javax.swing.JPanel player4;
    private javax.swing.JProgressBar timerProgressBar;
    // End of variables declaration                   
}